### ISSUE TITLE
Changelog or Release Notes

### ISSUE THREAD

**Issue by Harmon758** [Clarifai/clarifai-python-grpc#11]
Providing a changelog or release notes of any sort would be helpful in determining what each update added or changed.
For example, version 7.0.0 seems to only be [a single commit](https://github.com/Clarifai/clarifai-python-grpc/commit/b1551b929fa827cf7ff72014bb19407b23d57c37) that just bumps the version number?

**Comment by jeffreytoffoli** [comment]
You can view our changelog here: https://docs.clarifai.com/product-updates/changelog
