### ISSUE TITLE
How can I get coordinates of bounding box?

### ISSUE THREAD

**Issue by isikozsoy** [Clarifai/clarifai-python-grpc#56]
Hi,
I am currently using Apparel Detection model. I was able to obtain the prediction and their scores. However, I could not find a way to see get the bounding box coordinates. Can you help me with this? Thanks for your time.

Best,
Işık

**Comment by isikozsoy** [comment]
I am currently using the following code;

from clarifai_grpc.grpc.api import service_pb2, resources_pb2
from clarifai_grpc.grpc.api.status import status_code_pb2
from clarifai_grpc.channel.clarifai_channel import ClarifaiChannel
from clarifai_grpc.grpc.api import service_pb2_grpc


CLARIFAI_API_KEY = 'my-api-key'


# This is how you authenticate.
metadata = (('authorization', f'Key {CLARIFAI_API_KEY}'),)

stub = service_pb2_grpc.V2Stub(ClarifaiChannel.get_grpc_channel())

request = service_pb2.PostModelOutputsRequest(
    # This is the model ID of a publicly available General model. You may use any other public or custom model ID.
    model_id='e0be3b9d6a454f0493ac3a30784001ff',
    inputs=[
      resources_pb2.Input(data=resources_pb2.Data(image=resources_pb2.Image(url='https://cdn.dsmcdn.com/mnresize/1200/1800/ty5/product/media/images/20200629/9/3603078/75499541/1/1_org_zoom.jpg')))
    ])

response = stub.PostModelOutputs(request, metadata=metadata)

if response.status.code != status_code_pb2.SUCCESS:
    print("There was an error with your request!")
    print("\tCode: {}".format(response.outputs[0].status.code))
    print("\tDescription: {}".format(response.outputs[0].status.description))
    print("\tDetails: {}".format(response.outputs[0].status.details))
    raise Exception("Request failed, status code: " + str(response.status.code))

print(response)

**Comment by chungisaac** [comment]
Hi @isikozsoy , from the model ID it seems like you are using the Apparel classifier. Clarifai offers an Apparel Detector with model id `72c523807f93e18b431676fb9a58e6ad`, or in my public account it shows up as `apparel-detection`. The bounding box for the first output can be accessed in the response via `outputs[0].data.regions`, and the first bounding box can be accessed via `outputs[0].data.regions[0].region_info.bounding_box`. You should see fields "top_row" (y0), "left_col" (x0), "bottom_row" (y1), "right_col" (x1).

**Comment by chungisaac** [comment]
Let us know if this resolves your issue so that we can close this.

**Comment by isikozsoy** [comment]
It solved my problem, thanks a lot!
