### ISSUE TITLE
where can i get the model_id？

### ISSUE THREAD

**Issue by shaoniana1997** [Clarifai/clarifai-python-grpc#62]
Hello, the model_id for general model is model_id='aaa03c23b3724a16a56b629203edc62c'
But my model is General_detection, what is the id for general_detection?
Thanks!

**Comment by Cjkjvfnby** [comment]
Hi, 

You could always find a model in UI and get it's ID.  

For example, you could scroll to the bottom and find ID field or grab it from the URL. 
https://clarifai.com/clarifai/main/models/general-image-recognition

PS. IDs for models look more human-readable now.

**Comment by shaoniana1997** [comment]
Thank you for your nice idea -)

**Comment by shaoniana1997** [comment]
Hello, prehaps i have another question.
Here is the code and error, can you give me some useful advice?
---------------------------------------------------------------------------------------
from clarifai_grpc.channel.clarifai_channel import ClarifaiChannel
from clarifai_grpc.grpc.api import service_pb2_grpc
stub = service_pb2_grpc.V2Stub(ClarifaiChannel.get_grpc_channel())
from clarifai_grpc.grpc.api import service_pb2, resources_pb2
from clarifai_grpc.grpc.api.status import status_code_pb2

# Insert here the initialization code as outlined on this page:
# https://docs.clarifai.com/api-guide/api-overview/api-clients#client-installation-instructions

# This is how you authenticate.
metadata = (('authorization', f'Key {"d8801dd7d10942dc926ef5dcf1b853f3"}'),)

request = service_pb2.PostModelOutputsRequest(
    # This is the model ID of a publicly available General model. You may use any other public or custom model ID.
    model_id='aa7f35c01e0642fda5cf400f543e7c40',
    inputs=[
      resources_pb2.Input(data=resources_pb2.Data(image=resources_pb2.Image(url='https://samples.clarifai.com/metro-north.jpg')))
    ])
response = stub.PostModelOutputs(request, metadata=metadata)

if response.status.code != status_code_pb2.SUCCESS:
    print("There was an error with your request!")
    print("\tCode: {}".format(response.outputs[0].status.code))
    print("\tDescription: {}".format(response.outputs[0].status.description))
    print("\tDetails: {}".format(response.outputs[0].status.details))
    raise Exception("Request failed, status code: " + str(response.status.code))

for concept in response.outputs[0].data.concepts:
    print('%12s: %.2f' % (concept.name, concept.value))
-----------------------------------------------------------
error:
There was an error with your request!
Traceback (most recent call last):
  File "predict_concept.py", line 23, in <module>
    print("\tCode: {}".format(response.outputs[0].status.code))
IndexError: list index (0) out of range
------------------------------------------------------

**Comment by shaoniana1997** [comment]
Hello, i have another error，here is the detail of my code and error:
------------------------------------------------------------------------------------
from clarifai_grpc.channel.clarifai_channel import ClarifaiChannel
from clarifai_grpc.grpc.api import service_pb2_grpc
stub = service_pb2_grpc.V2Stub(ClarifaiChannel.get_grpc_channel())
from clarifai_grpc.grpc.api import service_pb2, resources_pb2
from clarifai_grpc.grpc.api.status import status_code_pb2
metadata = (('authorization', f'Key {"d8801dd7d10942dc926ef5dcf1b853f3"}'),)

request = service_pb2.PostModelOutputsRequest(
    # This is the model ID of a publicly available General model. You may use any other public or custom model ID.
    model_id='aa7f35c01e0642fda5cf400f543e7c40',
    inputs=[
      resources_pb2.Input(data=resources_pb2.Data(image=resources_pb2.Image(url='https://samples.clarifai.com/metro-north.jpg')))
    ])
response = stub.PostModelOutputs(request, metadata=metadata)

if response.status.code != status_code_pb2.SUCCESS:
    print("There was an error with your request!")
    print("\tCode: {}".format(response.outputs[0].status.code))
    print("\tDescription: {}".format(response.outputs[0].status.description))
    print("\tDetails: {}".format(response.outputs[0].status.details))
    raise Exception("Request failed, status code: " + str(response.status.code))
for concept in response.outputs[0].data.concepts:
    print('%12s: %.2f' % (concept.name, concept.value))
---------------------------------------------------------------------------
error:
There was an error with your request!
Traceback (most recent call last):
  File "predict_concept.py", line 23, in <module>
    print("\tCode: {}".format(response.outputs[0].status.code))
IndexError: list index (0) out of range

**Comment by shaoniana1997** [comment]
can you give me some useful advice? @Cjkjvfnby

**Comment by Cjkjvfnby** [comment]
I usually print the whole response.
```python
if response.status.code != status_code_pb2.SUCCESS:
    print(response)
```

PS. Please change your auth key and never post it in public. 
PPS. Use GitHub markdown for code. 
<img width="529" alt="image" src="https://user-images.githubusercontent.com/171597/159643748-ba243bde-34fa-49b9-9ae4-77af4c74938b.png">

**Comment by shaoniana1997** [comment]
I try it , wait a moment

**Comment by shaoniana1997** [comment]
status {
  code: MODEL_DOES_NOT_EXIST
  description: "Model does not exist"
  details: "Model \'aa7f35c01e0642fda5cf400f543e7c40\' does not exist."
  req_id: "97efb6d6fc9ac00c5426d53e3928eb75"
}
Traceback (most recent call last):
  File "predict_concept.py", line 29, in <module>
    for concept in response.outputs[0].data.concepts:
IndexError: list index (0) out of range

**Comment by shaoniana1997** [comment]
status {
  code: MODEL_DOES_NOT_EXIST
  description: "Model does not exist"
  details: "Model \'aa7f35c01e0642fda5cf400f543e7c40\' does not exist."
  req_id: "97efb6d6fc9ac00c5426d53e3928eb75"
}

Traceback (most recent call last):
  File "predict_concept.py", line 29, in <module>
    for concept in response.outputs[0].data.concepts:
IndexError: list index (0) out of range

It means the model does not exist,does the model_id is wrong?

**Comment by Cjkjvfnby** [comment]
> It means the model does not exist,does the model_id is wrong?

Try:  `general-image-detection`

<img width="302" alt="image" src="https://user-images.githubusercontent.com/171597/159647193-4f54760c-c404-4609-ae5f-f3c9f0568aaa.png">

**Comment by shaoniana1997** [comment]
Thank you for your nice advide and it always have trouble, here is the detail :
status {
  code: FAILURE
  description: "Failure"
  req_id: "15f8974d1e7922c2df8cd0e1a8967718"
}
outputs {
  id: "1789e17da1674dbf88f276a441eb291d"
  status {
    code: CONN_DOES_NOT_EXIST
    description: "Resource does not exist"
    details: "Could not find concepts (ai_xdMdHrPG,ai_Jl5BnRwm,ai_PN414qLW,ai_FdpKm4Cn,ai_B6CmnJKC,ai_8pMK1P1J,ai_B6gp3Zvv,ai_7vbh3VDw,ai_0JqcJtMV,ai_PQt6CD3H) in DB for lang: zh. Do these IDs exist and these concepts have translations for this language?"
  }

**Comment by Cjkjvfnby** [comment]
It seems that you are is trying to use not English language, but not all of the concepts have translations for this language. I would suggest switching the default language to English for your app and try again. Or at least provide the Model -> Languages -> [‘en’] parameter in the PostModelOutputsRequest.

**Comment by shaoniana1997** [comment]
Thank you for your patient guidance, it finally workds.
I have another question to bother you ,because the image is from url, if i want to use the API to predict concept for the pictures from my computer, what should i do ?

**Comment by Cjkjvfnby** [comment]
Replace URL with image  content. 

```python
with open(image_path, 'rb') as f:
   image_bytes = f.read()
...
image=Image(base64=image_bytes)
...
```

**Comment by shaoniana1997** [comment]
thank you ,i will try that

**Comment by shaoniana1997** [comment]
what does this mean?
status {
  code: FAILURE
  description: "Failure"
  req_id: "6dd084d3cd1a9cf2b29f989e582cc1cc"
}
outputs {
  id: "2e687c93de584b149c56daabd402c1a6"
  status {
    code: CONN_EXCEEDS_LIMITS
    description: "Account limits exceeded"
    details: "Request exceeds \"Pre-built classification model predict ops\" limit. Please contact support@clarifai.com or upgrade your plan."
  }
  created_at {
    seconds: 1651037978
    nanos: 337907595
  }
  model {
    id: "general-image-recognition"
    name: "general"
    created_at {
      seconds: 1457543499
      nanos: 608845000
    }
    app_id: "main"
    output_info {
      output_config {
      }
      message: "Show output_info with: GET /models/{model_id}/output_info"
      fields_map {
        fields {
          key: "concepts"
          value {
            string_value: "softmax"
          }
        }
      }
    }
    model_version {
      id: "aa7f35c01e0642fda5cf400f543e7c40"
      created_at {
        seconds: 1520370624
        nanos: 454834000
      }
      status {
        code: MODEL_TRAINED
        description: "Model is trained and ready"
      }
      visibility {
        gettable: PUBLIC
      }
      app_id: "main"
      user_id: "clarifai"
      metadata {
      }
    }
    user_id: "clarifai"
    input_info {
      fields_map {
        fields {
          key: "image"
          value {
            string_value: "images"
          }
        }
      }
    }
    train_info {
    }
    model_type_id: "visual-classifier"
    visibility {
      gettable: PUBLIC
    }
    modified_at {
      seconds: 1648153319
      nanos: 760183000
    }
    import_info {
    }
  }
  input {
    id: "9a14951475534f9fb8b72cbbc41c241f"
    data {
      image {
        url: "https://samples.clarifai.com/placeholder.gif"
        base64: "true"
      }
    }
  }
  data {
  }
}
@Cjkjvfnby @rok-povsic

**Comment by chungisaac** [comment]
@shaoniana1997 this seems to be a discussion suited for the [community slack](https://join.slack.com/t/clarifaicommunity/shared_invite/zt-nbyc5asz-MmV~fW2MDhDS6LfkWP1gkw) rather than an issue, we are more than happy to continue to help you there :) Closing this issue now.
